name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Output Debug
      uses: hmarr/debug-action
    - name: Checkout 
      uses: actions/checkout@v1
    - name: Installing PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.3
        extension-csv: mbstring, xdebug #optional
