name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout 
      uses: actions/checkout@v1
    - name: Installing PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.3
        extension-csv: mbstring, xdebug
#    - name: Check PHP and Composer Version 
#      run: php -v && composer -V
#    - name: Check PHP Extensions
#      run: php -m
    - name: Composer install
      run: composer install
    - name: Show Environment
      run: env |sort
    - name: Show files
      run: |
        pwd
        find .
        du -sh
#    - name: Show Installed Packages
#      run: apt list --installed
    - name: Create archive
      run: |
        NAME="../$(basename $PWD)-${GITHUB_SHA}.tar.xz"
        echo $NAME
        rm -fr .git/
        tar cvfJ $NAME --exclude-vcs .    # --exclude-from=.gitignore
        ln $NAME ../archive.xz            # makes it easier for artifacts
    - name: Show files
      run: |
        ls -la ..
        du -sh ../*
#    - uses: actions/upload-artifact@master
#      with:
#        name: archive
#        path: ../archive.xz
    - uses: darkflib/s3-sync-action@master
      with:
        args:  --endpoint-url=https://s3.eu-central-1.wasabisys.com  --acl public-read --follow-symlinks --delete
      env:
        SOURCE_DIR: './'
        AWS_REGION: 'eu-central-1'
        AWS_S3_BUCKET: 'wwff-sites/startpage'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
